name: Auto Build DEVLOG.md
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install apt packages
        run: sudo apt update && sudo apt install -yy grep binutils-multiarch

      - name: Building DEVLOG.md
        run: |
          cp -f posts/_meta/* _meta/
          ./composer-linux
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Regenerate DEVLOG.md"
          git push
